title: GURU Network â€“ The AI Orchestration Network
author:
  name: guru_network
  email: evgeny@dex.guru

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.

# Build settings

plugins:
  - jekyll-seo-tag
#   - jekyll-feed

partners:
  - { key: shimacapital, url: "#" }
  - { key: huobiventures, url: "#" }
  - { key: d1ventures, url: "#" }
  - { key: wintermute, url: "#" }
  - { key: honeydao, url: "#" }
  - { key: mirana, rl: "#" }
  - { key: impossiblefinance, url: "#" }
  - { key: woodstock, url: "#" }
  - { key: legoscapital, url: "#" }
  - { key: nimacapital, url: "#" }
  - { key: supernova, url: "#" }
  - { key: paraficapital, url: "#" }
  - { key: divergenceventures, url: "#" }
  - { key: thelao, url: "#" }
  - { key: lemniscap, url: "#" }
  - { key: stakecapital, url: "#" }
  - { key: bitscalecapital, url: "#" }

menu:
  - {
      title: Products,
      dropdown:
        [
          {
            items:
              [
                {
                  icon: dna,
                  title: Guru Block Explorer,
                  description: Analitics Driven Block Explorer for GEN,
                  url: https://b2b.dex.guru/explorer,
                },

                {
                  icon: floppy,
                  title: GEN Data Warehouse,
                  description: "For most data-intensive
                    applications like analytics,
                    AI,
                    ML,
                    etc.",
                  url: https://warehouse.dex.guru,
                },

                {
                  icon: yoga,
                  title: GEN DeFi Trading Terminal,
                  description: We provide users with real-time data,
                  trading charts,
                  and various features to help them make informed decisions when trading cryptocurrencies.,
                  url: https://dex.guru,
                },
              ],
          },
          {
            items:
              [
                {
                  title: "GEN AI Processor as a Service",
                  description: We provide users with real-time data,
                  url: /network.html,
                },

                {
                  title: GEN Wallet,
                  description: "Gateway To Participate",
                  url: /sdk.html,
                },

                {
                  title: $GURU Tokenomics,
                  Allocation and Distribution,
                  description: "$GURU Token Network Utility",
                  url: /distribution.html,
                },
              ],
          },
        ],
    }
  - {
      title: Community,
      url: "https://webforms.pipedrive.com/f/6rExdWpdC4j2tsyB09LRGHr6990s7NqeLfhIpT4vPjJOmddqhyIMu7dyvJFAjABNHd",
      dropdown:
        [
          {
            items:
              [
                { title: "Twitter", url: "https://twitter.com/dexguru" },
                { title: "Telegram", url: "https://t.me/dexguru" },
                { title: "Discord", url: "https://discord.gg/dPW8fzwzz9" },
              ],
          },
        ],
    }
  - {
      title: Resources,
      dropdown:
        [
          {
            title: "Guru Multi-Chain AI Compute Layer",
            items:
              [
                {
                  title: "Litepaper",
                  url: "/assets/img/litepapper_dexguru_network.pdf",
                },
                {
                  title: "Interoperability Architecture Whitepaper",
                  url: "/assets/img/guru_network_architecture_whitepaper.pdf",
                },
              ],
          },
        ],
    }
  - { title: Ecosytem, url: "#ecosystem" }
  - { title: Docs, url: https://docs.gurunetwork.ai/ }

aside:
  - { title: Flow Orchestraror App, url: https://warehouse.dex.guru }

# Generate social links in footer.
social_links:
  - { platform: twitter, user_url: "https://twitter.com/xgurunetwork" }
  - { platform: telegram, user_url: "https://t.me/dexguru" }
  - { platform: discord, user_url: "https://discord.gg/dPW8fzwzz9" }
